authors:
  fernanda:
    name: Fernanda Liendo
    description: DEVSENSE
    avatar: https://avatars.githubusercontent.com/u/41991783?v=4
    url: https://github.com/Fernandaliendo
  jakub:
    name: Jakub Misek
    description: DEVSENSE
    avatar: https://avatars.githubusercontent.com/u/842150?v=4
    url: https://x.com/misekjakub
  miloslav:
    name: Miloslav Beno
    description: DEVSENSE
    avatar: https://avatars.githubusercontent.com/u/842147?v=4
    url: https://x.com/miloslavbeno
  admin:
    name: Admin
    description: DEVSENSE
    avatar: https://avatars.githubusercontent.com/u/583231?v=4
  JohnHummel:
    name: John Hummel
    description: Contributor 
    avatar: https://avatars.githubusercontent.com/u/36854049?v=4
  maros:
    name: Maros Beno
    description: Contributor 
    avatar: https://avatars.githubusercontent.com/u/27303270?v=4
    url: https://github.com/marosbeno
  harikrishna:
    name: Harikrishna
    description: Contributor 
    avatar: https://avatars.githubusercontent.com/u/583231?v=4
