<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "title": "Blog",
    "slogan": "Welcome to Devsense's blog",
    "description": "News, announcements and tutorials for the PHP Tools Community.",
    "footer": "Copyright \u00a9 2020",
    "itemsPerPage": 8,
    "language": "en",
    "locale": "en, en_US, en_AU, en_CA, en_GB, en_IE, en_NZ",
    "timezone": "America\/New_York",
    "theme": "mediumish",
    "adminTheme": "booty",
    "homepage": "",
    "pageNotFound": "",
    "uriPage": "\/",
    "uriTag": "\/tag\/",
    "uriCategory": "\/category\/",
    "uriBlog": "",
    "url": "https:\/\/blog.devsense.com",
    "emailFrom": "no-reply@devsense-blog.azurewebsites.net",
    "orderBy": "date",
    "currentBuild": 20190530,
    "twitter": "https:\/\/twitter.com\/php4vs",
    "facebook": "https:\/\/www.facebook.com\/ph4vs\/",
    "codepen": "",
    "github": "https:\/\/github.com\/DEVSENSE",
    "instagram": "",
    "gitlab": "",
    "linkedin": "https:\/\/www.linkedin.com\/company\/1679437",
    "dateFormat": "F j, Y",
    "extremeFriendly": true,
    "autosaveInterval": 2,
    "titleFormatHomepage": "{{site-slogan}} | {{site-title}}",
    "titleFormatPages": "{{page-title}} | {{site-title}}",
    "titleFormatCategory": "{{category-name}} | {{site-title}}",
    "titleFormatTag": "{{tag-name}} | {{site-title}}",
    "imageRestrict": true,
    "imageRelativeToAbsolute": false,
    "logo": "BLUDIT.png",
    "mastodon": "",
    "thumbnailWidth": 320,
    "thumbnailHeight": 320,
    "thumbnailQuality": 75,
    "markdownParser": true
}